API_KEY = 'YOUR API KEY'
API_SECRET = 'YOUR SECRET KEY'

invest_amount=  'number'
min_amount= 10.5 

M1 = "KLINE_INTERVAL_1MINUTE"
M3 = "Client.KLINE_INTERVAL_3MINUTE" 
M5 = "Client.KLINE_INTERVAL_5MINUTE" 
M15 =  "Client.KLINE_INTERVAL_15MINUTE" 
M30 =  "Client.KLINE_INTERVAL_30MINUTE" 
H1  =  "Client.KLINE_INTERVAL_1HOUR"
H2  =  "Client.KLINE_INTERVAL_2HOUR"
H4  =  "Client.KLINE_INTERVAL_4HOUR"
H6  =  "Client.KLINE_INTERVAL_6HOUR"
H8  =  "Client.KLINE_INTERVAL_8HOUR"
H12 =  "Client.KLINE_INTERVAL_12HOUR"
D1  =  "Client.KLINE_INTERVAL_1DAY"
D3  =  "Client.KLINE_INTERVAL_3DAY"
D7  =  "Client.KLINE_INTERVAL_1WEEK"
D30 =  "Client.KLINE_INTERVAL_1MONTH"

HOUR = "hour ago UTC"
MINUTES ="min ago"